version: '3.8'

services:
  postgres_dw:
    image: postgres:15
    container_name: postgres_dw
    environment:
      #valor por defecto tras el ':-'
      POSTGRES_USER: ${POSTGRES_USER:-data_engineer}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD:-data_password}
      POSTGRES_DB: ${POSTGRES_DB:-ecommerce_dw}
    ports:
      - "${POSTGRES_PORT}:5432"
    volumes:
      - postgres_data:/var/lib/postgresql/data
    healthcheck:
      test: ["CMD-SHELL", "pg_isready -U ${POSTGRES_USER} -d ${POSTGRES_DB}"]
      interval: 5s
      timeout: 5s
      retries: 5

  airflow:
    build: .
    container_name: airflow_standalone
    command: standalone
    environment:
      - AIRFLOW__CORE__LOAD_EXAMPLES=False
      - AIRFLOW__CORE__EXECUTOR=SequentialExecutor
      - POSTGRES_HOST=postgres_dw
      - POSTGRES_PORT=5432
      - POSTGRES_USER=${POSTGRES_USER:-data_engineer}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD:-data_password}
      - POSTGRES_DB=${POSTGRES_DB:-ecommerce_dw}
    ports:
      - "8080:8080"
    volumes:
      - ./dags:/opt/airflow/dags
      - ./dbt_ecommerce:/opt/airflow/dbt_ecommerce
      - ./data:/opt/airflow/data
      - ./scripts:/opt/airflow/scripts
    depends_on:
      postgres_dw:
        condition: service_healthy

volumes:
  postgres_data: